version: "2"
services:
  plone:
    image: plone:4
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/eea.dexterity.themes
    environment:
      ADDONS: "eea.dexterity.themes[test]"
      DEVELOP: "src/eea.dexterity.themes"
